### ISSUE TITLE
repository cannot be cloned

### ISSUE THREAD

**Issue by becknet** [skills17/competition-manager#3]
When we try to clone the repository we get an error message:

```
git -v
git version 2.44.0

git clone git@github.com:skills17/competition-manager.git
Klone nach 'competition-manager'...
git@github.com: Permission denied (publickey).
Schwerwiegend: Konnte nicht vom Remote-Repository lesen.

Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
und das Repository existiert.
```

**Comment by sebastianhaeni** [comment]
Please verify if you can clone any other Github repo via SSH. I suspect issues on your client here and not anything faulty with the repository.

Btw, you can also try this

```
git clone https://github.com/skills17/competition-manager.git
```

**Comment by becknet** [comment]
thanks for the quick reply, the problem has been solved by using the URL you specified or by using an ssh key.

**Comment by sebastianhaeni** [comment]
Great! Let me know if there are any other issues.
